# Generated by Django 2.2.19 on 2022-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221012_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
